@echo off 

set /p IP_Addr=
SET LOCALIP=127.0.0.106
SET REMOTEHOST=10.1.101.106
SET LOCALPORT=5900
SET REMOTEPORT=5900
SET SSHSERVER=spiceworksexample.no-ip.org
SET USERNAME=sshuser
SET PASSWORD=password
SET SLEEP=5
SET PUTTYPATH=c:\putty.exe
SET EXEPATH="C:\Program Files\TightVNC\tvnviewer.exe"

start %PUTTYPATH% -N -L %LOCALIP%:%LOCALPORT%:%REMOTEHOST%:%REMOTEPORT% -l %USERNAME% -pw %PASSWORD% %SSHSERVER%
ping localhost -n %SLEEP%
%EXEPATH% %LOCALIP%::%LOCALPORT%